/**
 * Actions
 */
export * from './user.actions';
export * from './authen.actions';

export interface ActionReduxtype {
  type: string;
  payload?: any;
}

/**
 * Types
 */

// Authen
export const USER_TYPE = 'USER_TYPE';
export const UPDATE_USER_NOTI_SETTING = 'UPDATE_USER_NOTI_SETTING';
export const UPDATE_PROFILE_CUSTOMER_ADMIN = 'UPDATE_PROFILE_CUSTOMER_ADMIN';
export const AUTHEN_TYPE = 'AUTHEN_TYPE';
export const ENTER_PHONE_SCREEN = 'ENTER_PHONE_SCREEN';
export const VERIFICATION_ID_TYPE = 'VERIFICATION_ID_TYPE';

// Setting Admin
export const GET_SETTING_ADMIN = 'GET_SETTING_ADMIN';
export const LIST_SETTING_ADMIN = 'LIST_SETTING_ADMIN';
export const REMOVE_ITEM_SETTING_ADMIN = 'REMOVE_ITEM_SETTING_ADMIN';
export const CLEAR_SETTING_ADMIN = 'CLEAR_SETTING_ADMIN';

// Setting Supplier
export const GET_SUPPLIER = 'GET_SUPPLIER';
export const LIST_SUPPLIER = 'LIST_SUPPLIER';
export const REMOVE_ITEM_SUPPLIER = 'REMOVE_ITEM_SUPPLIER';
export const CLEAR_SUPPLIER = 'CLEAR_SUPPLIER';

// Treatment History Detail
export const GET_TREATMENT_HISTORY_DETAIL = 'GET_TREATMENT_HISTORY_DETAIL';
export const TREATMENT_HISTORY_DETAIL = 'TREATMENT_HISTORY_DETAIL';
export const TREATMENT_HISTORY_DETAIL_UPDATE_CARD = 'TREATMENT_HISTORY_DETAIL_UPDATE_CARD';
export const TREATMENT_HISTORY_DETAIL_UPDATE_SERVICE_CALENDAR =
  'TREATMENT_HISTORY_DETAIL_UPDATE_SERVICE_CALENDAR';
export const TREATMENT_HISTORY_DETAIL_UPDATE_PROMOTION =
  'TREATMENT_HISTORY_DETAIL_UPDATE_PROMOTION';

// Setting Clinic
export const LIST_CLINIC_TYPE = 'LIST_CLINIC_TYPE';
export const CLEAR_LIST_CLINIC = 'CLEAR_LIST_CLINIC';

export const SAVE_CITY_LOCATION = 'SAVE_CITY_LOCATION';
export const SAVE_DISTRICT_LOCATION = 'SAVE_DISTRICT_LOCATION';
export const SAVE_WARD_LOCATION = 'SAVE_WARD_LOCATION';

export const SAVE_SELECT_CITY_LOCATION = 'SAVE_SELECT_CITY_LOCATION';
export const SAVE_SELECT_DISTRICT_LOCATION = 'SAVE_SELECT_DISTRICT_LOCATION';
export const SAVE_SELECT_WARD_LOCATION = 'SAVE_SELECT_WARD_LOCATION';

export const RESET_SELECT_LOCATION = 'RESET_SELECT_LOCATION';
export const RESET_SELECT_CITY_LOCATION = 'RESET_SELECT_CITY_LOCATION';
export const RESET_SELECT_DISTRICT_LOCATION = 'RESET_SELECT_DISTRICT_LOCATION';
export const RESET_SELECT_WARD_LOCATION = 'RESET_SELECT_WARD_LOCATION';

export const LOCATION_TYPE_ACTION = {
  city: SAVE_CITY_LOCATION,
  district: SAVE_DISTRICT_LOCATION,
  ward: SAVE_WARD_LOCATION,
};

export const SELECT_LOCATION_TYPE_ACTION = {
  city: SAVE_SELECT_CITY_LOCATION,
  district: SAVE_SELECT_DISTRICT_LOCATION,
  ward: SAVE_SELECT_WARD_LOCATION,
};

export const SAVE_INFO_CLINIC_REQUEST = 'SAVE_INFO_CLINIC_REQUEST';
export const CLEAR_INFO_CLINIC_REQUEST = 'CLEAR_INFO_CLINIC_REQUEST';

export const UPDATE_PERMISSON_BUTTON = 'UPDATE_PERMISSON_BUTTON';
