const ListMachineData = [
  {
    id: 'MAC-001',
    name: 'Máy bán hàng tự động Cầu Giấy 1',
    turnover: 125000000,
    error: true,
    outOfStock: false,
    fullCash: true,
    process: 100,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-002',
    name: 'Máy bán hàng tự động Cầu Giấy 2',
    turnover: 125000000,
    error: false,
    outOfStock: false,
    fullCash: true,
    process: 50,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-003',
    name: 'Máy bán hàng tự động Cầu Giấy 3',
    turnover: 125000000,
    error: false,
    outOfStock: true,
    fullCash: false,
    process: 75,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-004',
    name: 'Máy bán hàng tự động Cầu Giấy 4',
    turnover: 125000000,
    error: false,
    outOfStock: false,
    fullCash: false,
    process: 10,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-005',
    name: 'Máy bán hàng tự động Cầu Giấy 5',
    turnover: 125000000,
    error: true,
    outOfStock: false,
    fullCash: false,
    process: 15,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-007',
    name: 'Máy bán hàng tự động Cầu Giấy 7',
    turnover: 125000000,
    error: false,
    outOfStock: true,
    fullCash: false,
    process: 50,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-008',
    name: 'Máy bán hàng tự động Cầu Giấy 8',
    turnover: 125000000,
    error: false,
    outOfStock: false,
    fullCash: true,
    process: 30,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-009',
    name: 'Máy bán hàng tự động Cầu Giấy 9',
    turnover: 125000000,
    error: true,
    outOfStock: false,
    fullCash: false,
    process: 80,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-0010',
    name: 'Máy bán hàng tự động Cầu Giấy 10',
    turnover: 125000000,
    error: true,
    outOfStock: true,
    fullCash: true,
    process: 15,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-0011',
    name: 'Máy bán hàng tự động Cầu Giấy 11',
    turnover: 125000000,
    error: true,
    outOfStock: true,
    fullCash: true,
    process: 73,
    location: 'Cầu giấy, Hà Nội',
  },
  {
    id: 'MAC-0012',
    name: 'Máy bán hàng tự động Cầu Giấy 12',
    turnover: 125000000,
    error: true,
    outOfStock: true,
    fullCash: true,
    process: 37,
    location: 'Cầu giấy, Hà Nội',
  },
];

export default ListMachineData;
