const ListHistoryData = [
  {
    time: new Date(),
    id: 'HIS-001',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-002',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-003',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-004',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-005',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-006',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-007',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-008',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-009',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-0010',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-0011',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-0012',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-0013',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-0014',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-0015',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-0016',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-0017',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
  {
    time: new Date(),
    id: 'HIS-0018',
    machine: 'Máy bán hàng tự động Cầu Giấy 1',
    staff: 'Nguyễn Ngọc Minh',
    location: 'Cầu giấy, Hà Nội',
    money: 10000000,
    start_time: new Date(),
    ennd_time: new Date(),
  },
];

export default ListHistoryData;
