FROM registry.hyperlogy.com/node:14-slim as builder
WORKDIR /vending-machine-web

COPY package.json ./
RUN npm install
RUN npm ci


FROM registry.hyperlogy.com/node:14-slim
WORKDIR /vending-machine-web

COPY --from=builder /vending-machine-web/node_modules node_modules
COPY . .

EXPOSE 3000
CMD ["npm", "run", "start:prod"]
